#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("CustomAdapter.Resource", IsApplication=true)]

namespace CustomAdapter
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int android = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int book = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int buzz = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int calculator = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int calendar = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int camera = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int card_background = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int custom_background = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int gallery = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Icon = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int maps = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int music = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int news = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int phone = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int sdk = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int store = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int twitter = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int voice = 2130837521;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060002
			public const int card_logo = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int card_subtitle = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int card_title = 2131099648;
			
			// aapt resource value: 0x7f060005
			public const int menu_default = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int menu_medium = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int menu_small = 2131099651;
			
			// aapt resource value: 0x7f060006
			public const int menuabout = 2131099654;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CardItem = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f050000
			public const int menu = 2131034112;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
